server:
  port: 8011

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver

    # 要生成哪个数据库的CRUD，就需要设置相应的连接地址
    # 生成 simpmart_commodity
#    url: jdbc:mysql://192.168.42.88:3306/simpmart_comm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=US/Eastern

    # 生成 simpmart_coupon
#    url: jdbc:mysql://192.168.42.88:3306/simpmart_prom?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=US/Eastern

    # 生成 simpmart_member
#    url: jdbc:mysql://192.168.42.88:3306/simpmart_memb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=US/Eastern

    # 生成 simpmart_order
#    url: jdbc:mysql://192.168.42.88:3306/simpmart_ordr?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=US/Eastern

    # 生成 simpmart_warehouse
    url: jdbc:mysql://192.168.42.88:3306/simpmart_ware?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=US/Eastern

    username: root
    password: root


    #oracle配置
    #    driverClassName: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@47.100.206.162:1521:xe
    #    username: renren
    #    password: 123456
    #SQLServer配置
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_fast
    #    username: sa
    #    password: 123456
    #PostgreSQL配置
  #    driverClassName: org.postgresql.Driver
  #    url: jdbc:postgresql://192.168.10.10:5432/renren_fast
  #    username: postgres
  #    password: 123456



  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/

#mongodb:
#  host: localhost
#  port: 27017
#  auth: false #是否使用密码验证
#  username: tincery
#  password: renren
#  source: 123456
#  database: test

mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql、mongodb】
renren:
  database: mysql

